routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Front\Home\FrontController@index')->name('front.home');
Route::get('/changelanguage/{langID?}', 'Front\Home\FrontController@changeLanguage')->name('changeLanguage');

Route::get('/loginadmin', 'Auth\LoginController@loginadmin')->name('loginadmin');
// Route::get('/loginfront', 'Auth\LoginController@registerfront')->name('loginfront');
Route::get('/registerfronts', 'Front\Home\FrontController@registerfront')->name('registerfronts');
Route::post('/loginfront', 'Auth\LoginController@storeloginfront')->name('storeloginfront');

// Route::get('/person/sync', 'Admin\PersonController@sync')->name('loginadmin');

Route::post('/sendmailcontacts', 'Front\Home\FrontController@sendEmailcontact')->name('front.sendmailfront');

Auth::routes();

Route::group(['middleware' => ['auth', 'role', 'web'], 'prefix' => 'admin'], function(){
	Route::get('/', 'HomeController@index')->name('home');

	/// Module Persons
	Route::post('/persons/input-person-role/{user_id}/{role_id}', 'Admin\PersonController@inputPersonRole')->name('persons.input-person-role');
	Route::delete('/persons/delete-person-role/{id}', 'Admin\PersonController@deletePersonRole')->name('persons.delete-person-role');
	Route::get('persons/getAPI', 'Admin\PersonController@getAPI')->name('persons.getAPI');
	Route::get('/persons/edit-ajax/{id}', 'Admin\PersonController@editAjax')->name('person.edit-ajax');
	Route::get('/persons/person-role/{user_id}', 'Admin\PersonController@personRole')->name('person.person-role');
	Route::get('/persons/list-of-role/{user_id}', 'Admin\PersonController@listOfRole')->name('person.list-of-role');
	Route::resource('persons', 'Admin\PersonController');
	//// end module person

	////Module Company
	Route::get('companies/get-datatables-data/{parent?}', 'Admin\CompanyController@getDatatablesData')->name('companies.getdatatablesdata');
	Route::get('companies/get-employee/{id}', 'Admin\CompanyController@getEmployee')->name('companies.get-employee');
	Route::get('companies/get-related-company/{id}', 'Admin\CompanyController@getRelatedCompany')->name('companies.get-related-company');
	Route::post('companies/save-related-company', 'Admin\CompanyController@saveRelatedCompany')->name('companies.save-related-company');
	Route::resource('companies', 'Admin\CompanyController');
	/////end company

	////Module Contentmanagement
	Route::get('nodes/{parent?}/{lvl?}/ajaxnode', 'Admin\NodeController@publish2ajaxnode')->name('nodes.ajaxnode');
	Route::post('/nodes/{id}/edit/priority', 'Admin\NodeController@nodePriority')->name('nodes.editpriority');
	Route::post('/nodes/{id}/edit/unlink', 'Admin\NodeController@nodeUnLink')->name('nodes.editunlink');
	Route::post('/nodes/{id}/edit/{parent?}', 'Admin\NodeController@nodeLink')->name('nodes.editlink');
	Route::get('/nodes/content-text/{id}', 'Admin\NodeController@contentText')->name('nodes.content-text');
	Route::get('/nodes/content-img/{id}', 'Admin\NodeController@contentImg')->name('nodes.content-img');
	Route::get('/nodes/content-detail/{id}', 'Admin\NodeController@contentDet')->name('nodes.content-detail');
	Route::put('/nodes/content-text/{id}', 'Admin\NodeController@contentTextUpdate')->name('nodes.content-text-update');
	Route::put('/nodes/content-img/{id}', 'Admin\NodeController@contentImgUpdate')->name('nodes.content-img-update');
	Route::resource('nodes', 'Admin\NodeController');
	/////end Contentmanagement


	////Module Statement
	Route::get('statements/ajax-list/{parent?}/{level?}', 'admin\StatementController@statementAjaxList')->name('statements.ajax-list');
	Route::get('statements/get-data-tables-data/{id?}', 'admin\StatementController@getDatatablesData')->name('statements.get-data-tables-data');
	Route::put('statements/link-unlink/{id?}/{parent?}', 'admin\StatementController@linkUnlink')->name('statements.link-unlink');
	Route::put('statements/priority/', 'admin\StatementController@priority')->name('statements.priority');
	Route::get('statements/get-product/{id?}', 'admin\StatementController@getProductData')->name('statements.get-product');
	Route::get('statements/get-product-all/{id?}', 'admin\StatementController@getProductDataAll')->name('statements.get-product-all');
	Route::get('statements/edit-ajax/{id?}', 'admin\StatementController@editAjax')->name('statements.edit-ajax');
	Route::put('statements/edit-tablename/{id?}', 'admin\StatementController@editTablename')->name('statements.edit-tablename');
	Route::put('statements/product-link/{id}', 'admin\StatementController@productLink')->name('statements.product-link');
	Route::resource('statements', 'admin\StatementController');
	/////end Statement

	/// Module Language String
	Route::get('/languagestring/', 'admin\LanguagestringController@index')->name('languagestring');
	Route::get('/languagestring/getLangs', 'admin\LanguagestringController@getLangs')->name('languagestring.getLangs');
	Route::post('/languagestring/store', 'admin\LanguagestringController@store')->name('languagestring.storeLangs');
	/// End Module Language String

	/// Module Product
	Route::get('products/{id}/edit-ajax', 'Admin\ProductController@editAjax')->name('product.editajax');
	Route::get('products/{id}/edit-product-text', 'Admin\ProductController@editProductText')->name('product.editproducttext');
	Route::put('products/update-ajax/{id}', 'Admin\ProductController@updateAjax')->name('product.updateajax');
	Route::get('products/{id}/edit-product-media', 'Admin\ProductController@editProductMedia')->name('product.editproductmedia');
	Route::post('products/update-product-media/{id?}', 'Admin\ProductController@updateProductMediaAjax')->name('product.updateproductmediaajax');
	Route::delete('products/delete-product-media/{id}', 'Admin\ProductController@deleteProductMediaAjax')->name('product.deleteproductmediaajax');
	Route::get('products/get-datatables-data', 'Admin\ProductController@getDatatablesData')->name('products.getdatatablesdata');
	Route::resource('products', 'Admin\ProductController');
	/// End Module Product

	// Module order sale
	Route::get('/ordersale/getDatatablesData', 'admin\OrderSaleController@getDatatablesData')->name('ordersale.getDatatablesData');
	Route::get('/ordersale/delete/{id}/{table?}', 'admin\OrderSaleController@delete')->name('ordersale.delete');
	Route::get('/ordersale/invoiced/{id}', 'admin\OrderSaleController@invoiced')->name('ordersale.invoiced');
	// End Module order sale

	////Sync Db to Wisehouse
	Route::get('/sync', 'admin\SyncwisehouseController@index')->name('sync.index');
	Route::get('/sync/range-product', 'admin\SyncwisehouseController@syncRangeProduct')->name('sync.rangeproduct');
	Route::get('/sync/product', 'admin\SyncwisehouseController@syncProduct')->name('sync.product');
	Route::get('/sync/company', 'admin\SyncwisehouseController@syncCompany')->name('sync.company');
	Route::get('/sync/extraques/{limit?}/{offset?}', 'admin\SyncwisehouseController@syncExtraquestion')->name('sync.extraques');
	Route::get('/sync/role', 'admin\SyncwisehouseController@syncRole')->name('sync.role');
	Route::get('/sync/statement', 'admin\SyncwisehouseController@syncStatement')->name('sync.statement');
	////Sync Db to Wisehouse

	////Module Roles
	Route::get('roles/get-datatables-data', 'admin\RoleController@getDatatablesData')->name('roles.getdatatablesdata');
	Route::get('roles/role-action-list', 'admin\RoleController@getRoleActionList')->name('roles.get-role-action-list');
	Route::get('roles/get-datatables-data-action', 'admin\RoleController@getDatatablesDataAction')->name('roles.getdatatablesdataaction');
	Route::get('roles/role-action-create', 'admin\RoleController@roleActionCreate')->name('roles.role-action-create');
	Route::post('roles/role-action-store', 'admin\RoleController@roleActionStore')->name('roles.role-action-store');
	Route::get('roles/role-action-edit/{id}', 'admin\RoleController@roleActionEdit')->name('roles.role-action-edit');
	Route::put('roles/role-action-update/{id}', 'admin\RoleController@roleActionUpdate')->name('roles.role-action-update');
	Route::resource('roles', 'admin\RoleController');
	/////end Roles
});

Route::resources([
    '/post' => 'Admin\PostController',
    '/node' => 'Admin\NodeController',
    '/admin/ordersale' => 'Admin\OrderSaleController',
    '/admin/ordersubscriptions' => 'Admin\OrdersubscriptionsController',
    '/admin/invoice' => 'Admin\InvoiceController',
    '/admin/registrations' => 'Admin\RegistrationController'
]);


Route::get('no/profiles', 'Front\Profile\ProfileController@index')->name('profiles.no.index');
Route::get('en/profiles', 'Front\Profile\ProfileController@index')->name('profiles.en.index');
Route::get('no/om_oss/{content?}', 'Front\Home\FrontController@omoss')->name('om_oss');

// My profile
Route::get('api-web/v1/profile/', 'Front\Api\ProfileController@index')->name('api.profile.index');
Route::put('api-web/v1/profile/update/{id?}', 'Front\Api\ProfileController@update')->name('api.profile.update');
Route::get('api-web/v1/profile/update/{id?}', 'Front\Api\ProfileController@edit')->name('api.profile.edit');

Route::get('api-web/v1/profile/updatepassword/{id?}', 'Front\Api\ProfileController@editPassword')->name('api.profile.editpassword');
Route::put('api-web/v1/profile/passwordstore/{id?}', 'Front\Api\ProfileController@passwordStore')->name('api.profile.passwordstore');

Route::get('api-web/v1/profile/subscription', 'Front\Api\ProfileController@subscription')->name('api.profile.subscription');

Route::get('api-web/v1/profile/yesdoit', 'Front\Api\ProfileController@yesdoit')->name('api.profile.yesdoit');

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Session;
use DataTables;
use Input;
use App\Entities\Admin\Role;
use App\Entities\Admin\Roleaction;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.roles.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = new Role();
        $role->Active = 1;
        return view('admin.roles.create', ['role' => $role]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'RoleName' => 'required',
        ]);


        $input = $request->all();

        $role = Role::create($input);
        return redirect()->route('roles.edit', $role->id)
                        ->with('success','Role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        return view('admin.roles.edit', ['role' => $role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $roleUpdate  = Role::where('id',$id)->first();
        if ($roleUpdate) {
           $role = $roleUpdate->update($request->all());
        }

        return redirect()->route('roles.edit', $id)
                        ->with('success','Company update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getDatatablesData()
    {
        $roles = Role::where('Active', 1);

        return DataTables::of($roles)
                ->addColumn('action', function ($roles) {

                                $edit = ' <a href="'.route('roles.edit', ['id' => $roles->id]).'" class="btn btn-xs btn-primary editProds">
                                            <i class="glyphicon glyphicon-edit"></i> Edit
                                        </a>';
                                $delete = ' <a href="'.route('roles.edit', ['id' => $roles->id]).'" class="btn btn-xs btn-danger editProds">
                                            <i class="glyphicon glyphicon-zoom-in"></i> Danger
                                        </a>';

                                return $edit.$delete;
                            })
                ->rawColumns(['Description', 'action'])
                ->make(true);
    }

    public function getRoleActionList()
    {
        return view('admin.roles.role-action-list');
    }

    public function getDatatablesDataAction()
    {
        $where = [
            ['RoleID', '!=', 0],
            ['Module', '!=', ''],
            ['Action', '!=', ''],
        ];
        $roles = Roleaction::where($where);

        return DataTables::of($roles)
                ->addColumn('action', function ($roles) {

                                $edit = ' <a href="'.route('roles.edit', ['id' => $roles->id]).'" class="btn btn-xs btn-primary editProds">
                                            <i class="glyphicon glyphicon-edit"></i> Edit
                                        </a>';
                                $delete = ' <a href="'.route('roles.edit', ['id' => $roles->id]).'" class="btn btn-xs btn-danger editProds">
                                            <i class="glyphicon glyphicon-zoom-in"></i> Danger
                                        </a>';

                                return $edit.$delete;
                            })
                ->rawColumns(['Description', 'action'])
                ->make(true);
    }

    public function roleActionCreate()
    {
        $role = new Roleaction();
        $role->Access = 1;
        $role->ChangedByPersonID = Auth::user()->id;
        $role->CreatedByPersonID = Auth::user()->id;

        $roles = Role::where('Active', 1)
                ->where([['RoleName', '!=', '']])
                ->orderBy('RoleName')->get();

        return view('admin.roles.create-action', ['role' => $role, 'roles' => $roles]);
    }

    public function roleActionStore(Request $request)
    {
        $this->validate($request, [
            'Module' => 'required',
            'Action' => 'required',
            'RoleID' => 'required',
        ]);


        $input = $request->all();

        $roleAction = Roleaction::create($input);
        return redirect()->route('roles.role-action-edit', $roleAction->id)
                        ->with('success','Company created successfully');
    }

    public function roleActionEdit($id)
    {
        $role = Roleaction::find($id);
        
        $roles = Role::where('Active', 1)
                ->where([['RoleName', '!=', '']])
                ->orderBy('RoleName')->get();

        return view('admin.roles.edit-action', ['role' => $role, 'roles' => $roles]);
    }

    public function roleActionUpdate(Request $request, $id)
    {
        $roleUpdate  = Roleaction::where('id',$id)->first();
        if ($roleUpdate) {
           $role = $roleUpdate->update($request->all());
        }

        return redirect()->route('roles.role-action-edit', $id)
                        ->with('success','Company update successfully');
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.master')

@section('title') 
Create Role
@endsection

@section('breadcrumb')
<h1>@yield('title')<!-- <small></small> --></h1>
<ol class="breadcrumb">
    <li><a href="{{ url('admin/') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active"><a href="{{ url('admin/roles') }}">Role</a></li>
    <li class="active"><a href="{{ route('roles.create') }}">@yield('title')</a></li>
</ol>
@endsection

@section('css_custom')
<link href="{{ URL::asset('assets/admin/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

<style type="text/css">
	.select2-container .select2-selection--single{
		height: 34px;
	}
</style>
@endsection

@section('content')
	<section class="content">

		@if(isset($role->id))
			<div class="row" style="margin-bottom: 15px;">
				<div class="col-md-4 text-center" style="margin-bottom: 15px;">
					<button class="btn btn-success btn-block productTextAjax" type="button" thirdparty="tinymce"
					target="{{ route('roles.edit', ['id' => $role->id, 'ajax' => 1]) }}">Role Detail</button>
				</div>

				<div class="col-md-4 text-center" style="margin-bottom: 15px;">
					<button class="btn btn-success btn-block productTextAjax" type="button"
					target="{{ route('roles.edit', ['id' => $role->id]) }}">Employee List</button>
				</div>

				<div class="col-md-4 text-center" style="margin-bottom: 15px;">
					<button class="btn btn-success btn-block productTextAjax" type="button" 
					target="{{ route('roles.edit', ['id' => $role->id]) }}">Related Company</button>
				</div>
			</div>
		@endif


		<form action="{{ route('roles.store') }}" method="post" enctype="multipart/form-data" id="upload_form">
		{{ csrf_field() }}
		@if(isset($role->id))
			<input type="hidden" name="id" value="{{ $role->id }}" />
			<input type="hidden" name="_method" value="PUT" />
		@endif

			<input type="hidden" name="Priority" value="0" />
			<input type="hidden" name="ChangedByPersonID" value="{{ Auth::user()->id }}" />
			<input type="hidden" name="CreatedByPersonID" value="{{ Auth::user()->id }}" />

		<div id="ajaxLoad">

		@if ($errors->any())
		    <div class="alert alert-danger">
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </div>
		@endif

		@if (\Session::has('success'))
      <div class="alert alert-success">
          <p>{{ \Session::get('success') }}</p>
      </div><br />
    @endif

		<div class="box box-success">
	    <div class="box-header with-border">
	      <h3 class="box-title">Role Data</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	      </div>
	    </div>
		    
		  <div class="box-body">
		    <div class="row">

		        <div class="col-xs-12">

              <div class="form-horizontal">

	              	<div class="row">
	              		<div class="col-md-6">

	              			<div class="form-group">
			                  <label for="RoleName" class="col-sm-3 control-label">Role name</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $role->RoleName or old('RoleName') }}" placeholder="Role name" name="RoleName">
			                  </div>
			                </div>

			                <div class="form-group">
			                  <label for="Description" class="col-sm-3 control-label">Description</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $role->Description or old('Description') }}" placeholder="Description" 
			                    name="Description">
			                  </div>
			                </div>
			                
		                </div>

		                {{-- ////////////////Kanan////////////////////// --}}
		                <div class="col-md-6">
		                	
		                	<div class="form-group">
			                  <label for="Interface" class="col-sm-3 control-label">Interface</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $role->Interface or old('Interface') }}" placeholder="Interface" name="Interface">
			                  </div>
			                </div>

			                
			                <div class="form-group">
			                  <label for="Active" class="col-sm-3 control-label">Active</label>

			                  <div class="col-sm-9">
			                  	@if($role->Active == 0)
			                    	<input type="checkbox" unchecked name="Active" style="position: relative;top: 7px;" value="1">
			                    @else
			                    	<input type="checkbox" checked name="Active" style="position: relative;top: 7px;" value="1">
			                    @endif
			                  </div>
			                </div>

		                </div>
	                </div>
	            </div>

		      	</div>

		    </div><!-- /.box-body -->
		  </div>
		</div>

	  <div class="panel">
			<div class="panel-body">
				<div class="row">
					<div class="col-md-offset-5 col-md-2 text-center">
						<a href="#" class="btn btn-default">Cancel</a>
						&nbsp;
						<input type="submit" value="Save" class="btn btn-primary" />
					</div>
				</div>
			</div>
		</div>

		</div> {{-- ///////////////Ajax Call///////////// --}}

		</form>

	</section>
@endsection

@section('addingFileJs')
	<script src="{{ URL::asset('assets/admin/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
	<script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=xspx9ax4f39yi8pjfnpoe60sz9x5mz1xewzmxt918nsl47sh"></script>
@endsection

@section('addingScriptJs')
	<script type="text/javascript">
	$(document).ready(function() {
			$('#PKPUsedDate').datepicker({
				autoclose: true,
				orientation: 'bottom',
				format: 'yyyy-mm-dd'
		  });

		  $('#InterestDate').datepicker({
				autoclose: true,
				orientation: 'bottom',
				format: 'yyyy-mm-dd'
		  });

		  $('#FoundedDate').datepicker({
				autoclose: true,
				orientation: 'bottom',
				format: 'yyyy-mm-dd'
		  });

	    tinymce.init({
						      selector: 'textarea',
						      entity_encoding : 'raw',
						      mode : 'specific_textareas',
						      //selector: 'textarea',
						      //editor_selector : 'mceEditor',
						      convert_urls: false,
						      language : 'en',
						      theme: 'modern',
						      plugins: [
						        'spellchecker,pagebreak,layer,table,save,insertdatetime,media,searchreplace,' +
						          'print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,' +
						          'nonbreaking,template,autoresize,' +
						          'anchor,charmap,hr,image,link,emoticons,code,textcolor,' +
						          'charmap,pagebreak'
						      ],
						      toolbar: 'insertfile undo redo| charmap | pagebreak | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image |  fontselect fontsizeselect | forecolor backcolor',
						      pagebreak_separator: "<!-- my page break -->",
						      image_advtab: true,
						      autoresize_max_height: 350
						    });

	    $('body').on('click', '.productTextAjax', function(){
	    	var target = $(this).attr('target');
	    	var thirdparty = $(this).attr('thirdparty');

	    	$.ajax({
	        method:"GET",
	        url:target,
	        success: function(result){
	            $("#ajaxLoad").html(result);

	            $('#getCompanyID').select2();

	            if(thirdparty == 'tinymce'){
	            	tinymce.remove();
	            	
	            	tinymce.init({
						      selector: 'textarea',
						      entity_encoding : 'raw',
						      mode : 'specific_textareas',
						      //selector: 'textarea',
						      //editor_selector : 'mceEditor',
						      convert_urls: false,
						      language : 'en',
						      theme: 'modern',
						      plugins: [
						        'spellchecker,pagebreak,layer,table,save,insertdatetime,media,searchreplace,' +
						          'print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,' +
						          'nonbreaking,template,autoresize,' +
						          'anchor,charmap,hr,image,link,emoticons,code,textcolor,' +
						          'charmap,pagebreak'
						      ],
						      toolbar: 'insertfile undo redo| charmap | pagebreak | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image |  fontselect fontsizeselect | forecolor backcolor',
						      pagebreak_separator: "<!-- my page break -->",
						      image_advtab: true,
						      autoresize_max_height: 350
						    });
	            }
	            
	        },
	        error: function(e){
	          alert("Error");
	          console.log(e);
	        }
	      });
	    });

	    

	    $('body').on('click', '.addComRelation', function(){
	    	// alert($('#getCompanyID').val());
	    	var formData = {
	                ToCompanyID : $('#getCompanyID').val(),
	                FromCompanyID : $('#CompanyID').val(),
	                FromCompanyRelationTypeID : 0,
	                ToCompanyRelationTypeID : 0,
	                Active : 1,
	                InsertedByPersonID : {{ Auth::user()->id }},
	                UpdatedByPersonID : {{ Auth::user()->id }},
	                _token  : $('meta[name="csrf-token"]').attr('content'),
	                _method: 'POST',
	            }

	      console.log(formData);
	      // return false;

	      $.ajax({
	        method:"POST",
	        url:"{{ route('companies.save-related-company') }}",
	        data: formData,
	        //dataType: "json",
	        success: function(result){
	            console.log(result);
	            if(result.error == 0){
	              alert("Update data Success");
	              $(".companyRelatedReload").load("{{ route('companies.get-related-company',$role->id) }} .companyRelatedReloadSuccess");
	              $(".successCompanyRelated").fadeIn('slow');
	            }else{
	            	alert("Error when update");
	            }

	        },
	        error: function(e, r){
	          alert("Error");
	          console.log(e);
	          console.log(r);
	        }
	      });
	    });
	});
	</script>
@endsection

resources/views/admin/roles/list.blade.php
@extends('admin.layouts.master')

@section('title') 
Roles 
@endsection

@section('breadcrumb')
<h1>@yield('title')<!-- <small></small> --></h1>
<ol class="breadcrumb">
    <li><a href="{{ url('admin/') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active"><a href="{{ url('admin/roles') }}">@yield('title')</a></li>
</ol>
@endsection

@section('css_custom')
<link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">
@endsection

@section('content')
	<section class="content">

		<div class="box collapsed-box">
	    <div class="box-header with-border">
	      <h3 class="box-title">Create New Roles</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-plus"></i></button>
	      </div>
	    </div>
	    <div class="box-body" style="display: none;">
	      <div class="row">

	        <div class="col-xs-12">
	        	<a class="btn btn-success" href="{{ route('roles.create') }}">Create New Role</a>
	        </div>

	      </div>

	    </div><!-- /.box-body -->
	  </div>

	  <!-- Default box -->
	  <div class="box">
	    <div class="box-header with-border">
	      <h3 class="box-title">Role</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	      </div>
	    </div>
	    <div class="box-body">
	      <div class="row">

	        <div class="col-xs-12">

	          	<div class="panel panel-default">
                	<div class="panel-heading">Role List</div>

	                <div class="panel-body">
	                    <table class="table table-hover table-bordered table-striped datatable" style="width:100%">
	                        <thead>
	                            <tr>
	                                <th>Role Id</th>
	                                <th>RoleName</th>
	                                <th>Description</th>
	                                <th>Last Update</th>
	                                <th>Action</th>
	                            </tr>
	                        </thead>
	                    </table>
	            	</div>
	            </div>

	        </div>

	      </div>
	      <div class="ajax-content">
	      </div>
	    </div>
	    <!-- /.box-body -->
	    <div class="box-footer">
	      Footer
	    </div>
	    <!-- /.box-footer-->
	  </div>
	  <!-- /.box -->

	</section>
@endsection

@section('addingFileJs')
	<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
@endsection

@section('addingScriptJs')
	<script type="text/javascript">
	$(document).ready(function() {
	    var table = $('.datatable').DataTable({
	        processing: true,
	        serverSide: true,
	        ajax: '{{ route('roles.getdatatablesdata') }}',
	        columns: [
	            {data: 'id', name: 'id'},
	            {data: 'RoleName', name: 'RoleName'},
	            {data: 'Description', name: 'Description'},
	            {data: 'updated_at', name: 'updated_at'},
	            {data: 'action', name: 'action', orderable: false, searchable: false}
	        ]
	    });
	});
	</script>
@endsection