routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Front\Home\FrontController@index')->name('front.home');
Route::get('/changelanguage/{langID?}', 'Front\Home\FrontController@changeLanguage')->name('changeLanguage');

Route::get('/loginadmin', 'Auth\LoginController@loginadmin')->name('loginadmin');
// Route::get('/loginfront', 'Auth\LoginController@registerfront')->name('loginfront');
Route::get('/registerfronts', 'Front\Home\FrontController@registerfront')->name('registerfronts');
Route::post('/loginfront', 'Auth\LoginController@storeloginfront')->name('storeloginfront');

// Route::get('/person/sync', 'Admin\PersonController@sync')->name('loginadmin');

Route::post('/sendmailcontacts', 'Front\Home\FrontController@sendEmailcontact')->name('front.sendmailfront');

Auth::routes();

Route::group(['middleware' => ['auth', 'role', 'web'], 'prefix' => 'admin'], function(){
	Route::get('/', 'HomeController@index')->name('home');

	/// Module Persons
	Route::post('/persons/input-person-role/{user_id}/{role_id}', 'Admin\PersonController@inputPersonRole')->name('persons.input-person-role');
	Route::delete('/persons/delete-person-role/{id}', 'Admin\PersonController@deletePersonRole')->name('persons.delete-person-role');
	Route::get('persons/getAPI', 'Admin\PersonController@getAPI')->name('persons.getAPI');
	Route::get('/persons/edit-ajax/{id}', 'Admin\PersonController@editAjax')->name('person.edit-ajax');
	Route::get('/persons/person-role/{user_id}', 'Admin\PersonController@personRole')->name('person.person-role');
	Route::get('/persons/list-of-role/{user_id}', 'Admin\PersonController@listOfRole')->name('person.list-of-role');
	Route::resource('persons', 'Admin\PersonController');
	//// end module person

	////Module Company
	Route::get('companies/get-datatables-data/{parent?}', 'Admin\CompanyController@getDatatablesData')->name('companies.getdatatablesdata');
	Route::get('companies/get-employee/{id}', 'Admin\CompanyController@getEmployee')->name('companies.get-employee');
	Route::get('companies/get-related-company/{id}', 'Admin\CompanyController@getRelatedCompany')->name('companies.get-related-company');
	Route::post('companies/save-related-company', 'Admin\CompanyController@saveRelatedCompany')->name('companies.save-related-company');
	Route::resource('companies', 'Admin\CompanyController');
	/////end company

	////Module Contentmanagement
	Route::get('nodes/{parent?}/{lvl?}/ajaxnode', 'Admin\NodeController@publish2ajaxnode')->name('nodes.ajaxnode');
	Route::post('/nodes/{id}/edit/priority', 'Admin\NodeController@nodePriority')->name('nodes.editpriority');
	Route::post('/nodes/{id}/edit/unlink', 'Admin\NodeController@nodeUnLink')->name('nodes.editunlink');
	Route::post('/nodes/{id}/edit/{parent?}', 'Admin\NodeController@nodeLink')->name('nodes.editlink');
	Route::get('/nodes/content-text/{id}', 'Admin\NodeController@contentText')->name('nodes.content-text');
	Route::get('/nodes/content-img/{id}', 'Admin\NodeController@contentImg')->name('nodes.content-img');
	Route::get('/nodes/content-detail/{id}', 'Admin\NodeController@contentDet')->name('nodes.content-detail');
	Route::put('/nodes/content-text/{id}', 'Admin\NodeController@contentTextUpdate')->name('nodes.content-text-update');
	Route::put('/nodes/content-img/{id}', 'Admin\NodeController@contentImgUpdate')->name('nodes.content-img-update');
	Route::resource('nodes', 'Admin\NodeController');
	/////end Contentmanagement


	////Module Statement
	Route::get('statements/ajax-list/{parent?}/{level?}', 'admin\StatementController@statementAjaxList')->name('statements.ajax-list');
	Route::get('statements/get-data-tables-data/{id?}', 'admin\StatementController@getDatatablesData')->name('statements.get-data-tables-data');
	Route::put('statements/link-unlink/{id?}/{parent?}', 'admin\StatementController@linkUnlink')->name('statements.link-unlink');
	Route::put('statements/priority/', 'admin\StatementController@priority')->name('statements.priority');
	Route::get('statements/get-product/{id?}', 'admin\StatementController@getProductData')->name('statements.get-product');
	Route::get('statements/get-product-all/{id?}', 'admin\StatementController@getProductDataAll')->name('statements.get-product-all');
	Route::get('statements/edit-ajax/{id?}', 'admin\StatementController@editAjax')->name('statements.edit-ajax');
	Route::put('statements/edit-tablename/{id?}', 'admin\StatementController@editTablename')->name('statements.edit-tablename');
	Route::put('statements/product-link/{id}', 'admin\StatementController@productLink')->name('statements.product-link');
	Route::resource('statements', 'admin\StatementController');
	/////end Statement

	/// Module Language String
	Route::get('/languagestring/', 'admin\LanguagestringController@index')->name('languagestring');
	Route::get('/languagestring/getLangs', 'admin\LanguagestringController@getLangs')->name('languagestring.getLangs');
	Route::post('/languagestring/store', 'admin\LanguagestringController@store')->name('languagestring.storeLangs');
	/// End Module Language String

	/// Module Product
	Route::get('products/{id}/edit-ajax', 'Admin\ProductController@editAjax')->name('product.editajax');
	Route::get('products/{id}/edit-product-text', 'Admin\ProductController@editProductText')->name('product.editproducttext');
	Route::put('products/update-ajax/{id}', 'Admin\ProductController@updateAjax')->name('product.updateajax');
	Route::get('products/{id}/edit-product-media', 'Admin\ProductController@editProductMedia')->name('product.editproductmedia');
	Route::post('products/update-product-media/{id?}', 'Admin\ProductController@updateProductMediaAjax')->name('product.updateproductmediaajax');
	Route::delete('products/delete-product-media/{id}', 'Admin\ProductController@deleteProductMediaAjax')->name('product.deleteproductmediaajax');
	Route::get('products/get-datatables-data', 'Admin\ProductController@getDatatablesData')->name('products.getdatatablesdata');
	Route::resource('products', 'Admin\ProductController');
	/// End Module Product

	// Module order sale
	Route::get('/ordersale/getDatatablesData', 'admin\OrderSaleController@getDatatablesData')->name('ordersale.getDatatablesData');
	Route::get('/ordersale/delete/{id}/{table?}', 'admin\OrderSaleController@delete')->name('ordersale.delete');
	Route::get('/ordersale/invoiced/{id}', 'admin\OrderSaleController@invoiced')->name('ordersale.invoiced');
	// End Module order sale

	////Sync Db to Wisehouse
	Route::get('/sync', 'admin\SyncwisehouseController@index')->name('sync.index');
	Route::get('/sync/range-product', 'admin\SyncwisehouseController@syncRangeProduct')->name('sync.rangeproduct');
	Route::get('/sync/product', 'admin\SyncwisehouseController@syncProduct')->name('sync.product');
	Route::get('/sync/company', 'admin\SyncwisehouseController@syncCompany')->name('sync.company');
	Route::get('/sync/extraques/{limit?}/{offset?}', 'admin\SyncwisehouseController@syncExtraquestion')->name('sync.extraques');
	Route::get('/sync/role', 'admin\SyncwisehouseController@syncRole')->name('sync.role');
	Route::get('/sync/statement', 'admin\SyncwisehouseController@syncStatement')->name('sync.statement');
	////Sync Db to Wisehouse

	////Module Roles
	Route::get('roles/get-datatables-data', 'admin\RoleController@getDatatablesData')->name('roles.getdatatablesdata');
	Route::get('roles/role-action-list', 'admin\RoleController@getRoleActionList')->name('roles.get-role-action-list');
	Route::get('roles/get-datatables-data-action', 'admin\RoleController@getDatatablesDataAction')->name('roles.getdatatablesdataaction');
	Route::get('roles/role-action-create', 'admin\RoleController@roleActionCreate')->name('roles.role-action-create');
	Route::post('roles/role-action-store', 'admin\RoleController@roleActionStore')->name('roles.role-action-store');
	Route::get('roles/role-action-edit/{id}', 'admin\RoleController@roleActionEdit')->name('roles.role-action-edit');
	Route::put('roles/role-action-update/{id}', 'admin\RoleController@roleActionUpdate')->name('roles.role-action-update');
	Route::resource('roles', 'admin\RoleController');
	/////end Roles
});

Route::resources([
    '/post' => 'Admin\PostController',
    '/node' => 'Admin\NodeController',
    '/admin/ordersale' => 'Admin\OrderSaleController',
    '/admin/ordersubscriptions' => 'Admin\OrdersubscriptionsController',
    '/admin/invoice' => 'Admin\InvoiceController',
    '/admin/registrations' => 'Admin\RegistrationController'
]);


Route::get('no/profiles', 'Front\Profile\ProfileController@index')->name('profiles.no.index');
Route::get('en/profiles', 'Front\Profile\ProfileController@index')->name('profiles.en.index');
Route::get('no/om_oss/{content?}', 'Front\Home\FrontController@omoss')->name('om_oss');

// My profile
Route::get('api-web/v1/profile/', 'Front\Api\ProfileController@index')->name('api.profile.index');
Route::put('api-web/v1/profile/update/{id?}', 'Front\Api\ProfileController@update')->name('api.profile.update');
Route::get('api-web/v1/profile/update/{id?}', 'Front\Api\ProfileController@edit')->name('api.profile.edit');

Route::get('api-web/v1/profile/updatepassword/{id?}', 'Front\Api\ProfileController@editPassword')->name('api.profile.editpassword');
Route::put('api-web/v1/profile/passwordstore/{id?}', 'Front\Api\ProfileController@passwordStore')->name('api.profile.passwordstore');

Route::get('api-web/v1/profile/subscription', 'Front\Api\ProfileController@subscription')->name('api.profile.subscription');

Route::get('api-web/v1/profile/yesdoit', 'Front\Api\ProfileController@yesdoit')->name('api.profile.yesdoit');

resources/views/admin/content-management/create.blade.php
@extends('admin.layouts.master')

@section('title')
Create Publish2
@endsection

@section('titlecontent')
Publish2
@endsection

@section('subtitlecontent')
create
@endsection

@section('content')
<section class="content">
  <!-- Default box -->
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Create Content Management Page</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                title="Collapse">
          <i class="fa fa-minus"></i></button>
        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fa fa-times"></i></button>
      </div>
    </div>
    <div class="box-body">
      <div class="link-back-to-list">
        <a href="{{ route('nodes.index') }}">Back to list</a>
        <hr />
      </div>

      @if (\Session::has('success'))
      <div class="alert alert-success">
          <p>{{ \Session::get('success') }}</p>
      </div><br />
      @endif


      {!! Form::open(array('route' => 'node.store','method'=>'POST', 'files' => true)) !!}
        {{ method_field('post') }}
        <input type="hidden" value="{{ $parent }}" name="parent">
        <div class="box-body">
          <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
            <label for="inputTitle1">Title</label>
            {!! Form::text('title', null, array('placeholder' => 'Field the title','class' => 'form-control')) !!}
            @if ($errors->has('title'))
                <span class="help-block">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            @endif
          </div>

          <div class="form-group {{ $errors->has('template') ? 'has-error' : '' }}">
            <label for="inputAlias">Template</label>
            {!! Form::select('template', $arrTemplates, null, ['placeholder' => 'Pick a Template','class' => 'form-control' ]) !!}
            @if ($errors->has('template'))
                <span class="help-block">
                    <strong>{{ $errors->first('template') }}</strong>
                </span>
            @endif
          </div>

          <div class="form-group {{ $errors->has('alias') ? 'has-error' : '' }}">
            <label for="inputAlias">Alias</label>
            {!! Form::text('alias', null, array('placeholder' => 'Field the alias','class' => 'form-control')) !!}
            @if ($errors->has('alias'))
                <span class="help-block">
                    <strong>{{ $errors->first('alias') }}</strong>
                </span>
            @endif
          </div>

          <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
            <label for="inputDescription">Description</label>
            {!! Form::text('description', null, array('placeholder' => 'Field the description','class' => 'form-control')) !!}
            @if ($errors->has('description'))
                <span class="help-block">
                    <strong>{{ $errors->first('description') }}</strong>
                </span>
            @endif
          </div>

          <div class="form-group {{ $errors->has('keyword') ? 'has-error' : '' }}">
            <label for="inputKeyword">Keyword</label>
            {!! Form::text('keyword', null, array('placeholder' => 'Field the keyword','class' => 'form-control')) !!}
            @if ($errors->has('keyword'))
                <span class="help-block">
                    <strong>{{ $errors->first('keyword') }}</strong>
                </span>
            @endif
          </div>

          <div class="form-group {{ $errors->has('content1') ? 'has-error' : '' }}">
            <label for="inputConten1">Content 1</label>
            {!! Form::textarea('content1', null, array('class' => 'form-control')) !!}
            @if ($errors->has('keyword'))
                <span class="help-block">
                    <strong>{{ $errors->first('keyword') }}</strong>
                </span>
            @endif
          </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      {!! Form::close() !!}
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
      Footer
    </div>
    <!-- /.box-footer-->
  </div>
  <!-- /.box -->

</section>
@endsection

resources/views/admin/content-management/index.blade.php
@extends('admin.layouts.master')

@section('title')
Content Management
@endsection

@section('titlecontent')
Content Management
@endsection

@section('subtitlecontent')
List
@endsection

@section('content')
	<section class="content">

		@if (\Session::has('success'))
      <div class="alert alert-success">
          <p>{{ \Session::get('success') }}</p>
      </div><br />
    @endif

	  <!-- Default box -->
	  <div class="box">
	    <div class="box-header with-border">
	      <h3 class="box-title">Conten Management Page</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
	          <i class="fa fa-times"></i></button>
	      </div>
	    </div>
	    <div class="box-body">
	      <div class="row">
	      	<div class="col-md-3">
	      		<div class="lvl1">
		      		<div class="h-new-node">
		      			<img src="{{ asset('images/folder1.png') }}" class="img-responsive" />
		      		</div>
		      		<div class="h-new-title">
		      			<a href="{{ route('nodes.create', ['parent' => 0, 'lvl' => 1]) }}">New Node</a>
		      		</div>

		      		<div class="clearfix"></div>

		      		<div class="b-node">
		      			@foreach($nodes as $node)
		      			<div class="c-menu-b">
			      			<div class="h-new-node">
			      				<a href="{{ URL::asset('/admin/nodes') }}?parent=$node->node->id/2/ajaxnode"
			      					id="{{ $node->node->id }}" class="lvl1clicked">
				      				<img src="{{ asset('images/folder1.png') }}" class="img-responsive" />
				      			</a>
				      		</div>
				      		<div class="h-new-title">
				      			<a href="{{ route('nodes.edit', ['id' => $node->node->id, 'parent' => session()->get('lvl1Val'), 'lvl' => $lvl]) }}">{{ $node->node->title }} ({{ $node->node->id }})</a>
				      		</div>

				      		<div class="clearfix"></div>
			      		</div>
			      		@endforeach

		      		</div>
	      		</div>

	      		<hr />
	      	</div>

	      	<div class="col-md-3 ajavlvl2">
	      		<hr />
	      	</div>

	      	<div class="col-md-3 ajavlvl3">
	      		<hr />
	      	</div>

	      	<div class="col-md-3 ajavlvl4">
	      		<hr />
	      	</div>

	      </div>
	    </div>
	    <!-- /.box-body -->
	    <div class="box-footer">
	      Footer
	    </div>
	    <!-- /.box-footer-->
	  </div>
	  <!-- /.box -->

	</section>
@endsection



{{-- /////////////////////////Jquery//////////////////////////////////// --}}
@section('addingScriptJs')
  <script type="text/javascript">

    $(document).ready(function(){

      $("body").on('click', '.lvl1clicked', function(e){
      	e.preventDefault();
      	var Parent = "{{ URL::asset('/admin/nodes') }}/"+$(this).attr('id')+"/2/ajaxnode";
      	$(".ajavlvl2").load(Parent);
      	$(".ajavlvl3load").remove();
      	$(".ajavlvl4load").remove();
      });

      $("body").on('click', '.lvl2clicked', function(e){
      	e.preventDefault();
      	var Parent = "{{ URL::asset('/admin/nodes') }}/"+$(this).attr('id')+"/3/ajaxnode";
      	$(".ajavlvl3").load(Parent);
      	$(".ajavlvl4load").remove();
      });

      $("body").on('click', '.lvl3clicked', function(e){
      	e.preventDefault();
      	var Parent = "{{ URL::asset('/admin/nodes') }}/"+$(this).attr('id')+"/4/ajaxnode";
      	$(".ajavlvl4").load(Parent);
      	//$(".ajavlvl4load").remove();
      });

    });

  </script>
@endsection

resources/views/admin/content-management/update-content-ajax.blade.php
  <!-- Default box -->
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Update Content Text Page</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                title="Collapse">
          <i class="fa fa-minus"></i></button>
        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fa fa-times"></i></button>
      </div>
    </div>
    <div class="box-body">

              <div class="form-group {{ $errors->has('content1') ? 'has-error' : '' }}"> 
                <label for="content1">Content</label>
                <textarea class="form-control" name="content1" type="text" id="content1">{{ $nodes->content1 }}</textarea>
                @if ($errors->has('content1'))
                    <span class="help-block">
                        <strong>{{ $errors->first('content1') }}</strong>
                    </span>
                @endif
              </div>

              <div class="form-group {{ $errors->has('content2') ? 'has-error' : '' }}">
                <label for="content2">Content 2</label>
                <textarea class="form-control" name="content2" type="text" id="content2">{{ $nodes->content2 }}</textarea>
                @if ($errors->has('content2'))
                    <span class="help-block">
                        <strong>{{ $errors->first('content2') }}</strong>
                    </span>
                @endif
              </div>

              <div class="form-group {{ $errors->has('content3') ? 'has-error' : '' }}">
                <label for="content3">Content 3</label>
                <textarea class="form-control" name="content3" type="text" id="content3">{{ $nodes->content3 }}</textarea>
                @if ($errors->has('content3'))
                    <span class="help-block">
                        <strong>{{ $errors->first('content3') }}</strong>
                    </span>
                @endif
              </div>

              <div class="form-group {{ $errors->has('content4') ? 'has-error' : '' }}">
                <label for="content4">Content 4</label>
                <textarea class="form-control" name="content4" type="text" id="content4">{{ $nodes->content4 }}</textarea>
                @if ($errors->has('content4'))
                    <span class="help-block">
                        <strong>{{ $errors->first('content4') }}</strong>
                    </span>
                @endif
              </div>

              <div class="box-footer">
                <button type="button" class="btn btn-primary save-node-content">Submit</button>
              </div>

    </div>
    <!-- /.box-body -->
    <!-- /.box-footer-->
  </div>
  <!-- /.box -->

resources/views/admin/content-management/update-detail-ajax.blade.php
  <!-- Default box -->
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Update Content Management Page</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                title="Collapse">
          <i class="fa fa-minus"></i></button>
        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fa fa-times"></i></button>
      </div>
    </div>
    <div class="box-body">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#node_detail" data-toggle="tab" aria-expanded="true">Node Detail</a></li>
          <li class="pull-right"><a href="{{ route('nodes.index') }}" class="text-muted">Back to list</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="node_detail">

            @if (\Session::has('success'))
            <div class="alert alert-success">
                <p>{{ \Session::get('success') }}</p>
            </div><br />
            @endif

              <div class="box-body">
                  <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    {{ Form::label('title', 'Title') }}
                    {{ Form::text('title', $nodes->title, array('class' => 'form-control')) }}

                    @if ($errors->has('title'))
                        <span class="help-block">
                            <strong>{{ $errors->first('title') }}</strong>
                        </span>
                    @endif
                  </div>

                  <div class="form-group {{ $errors->has('template') ? 'has-error' : '' }}">
                    {{ Form::label('template', 'Templates') }}
                    {{ Form::select('template', $arrTemplates, $nodes->template,
                                    ['placeholder' => 'Pick a Template...', 'class' => 'form-control']) }}

                    @if ($errors->has('keyword'))
                        <span class="help-block">
                            <strong>{{ $errors->first('keyword') }}</strong>
                        </span>
                    @endif
                  </div>


                  <div class="form-group {{ $errors->has('alias') ? 'has-error' : '' }}">
                    {{ Form::label('alias', 'Alias') }}
                    {{ Form::text('alias', $nodes->alias, array('class' => 'form-control')) }}

                    @if ($errors->has('alias'))
                        <span class="help-block">
                            <strong>{{ $errors->first('alias') }}</strong>
                        </span>
                    @endif
                  </div>

                  <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                    {{ Form::label('description', 'Description') }}
                    {{ Form::text('description', $nodes->description, array('class' => 'form-control')) }}

                    @if ($errors->has('description'))
                        <span class="help-block">
                            <strong>{{ $errors->first('description') }}</strong>
                        </span>
                    @endif
                  </div>

                  <div class="form-group {{ $errors->has('keyword') ? 'has-error' : '' }}">
                    {{ Form::label('keyword', 'Keyword') }}
                    {{ Form::text('keyword', $nodes->keyword, array('class' => 'form-control')) }}

                    @if ($errors->has('keyword'))
                        <span class="help-block">
                            <strong>{{ $errors->first('keyword') }}</strong>
                        </span>
                    @endif
                  </div>

                  <div class="form-group {{ $errors->has('active') ? 'has-error' : '' }}">
                    {{ Form::label('active', 'Active') }}
                    {{ Form::checkbox('active', 1, $nodes->active, ['class' => '']) }}
                  </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
              
          </div>
          <!-- /.tab-pane -->
          
        </div>
        <!-- /.tab-content -->
      </div>

    </div>
    <!-- /.box-body -->
    <!-- /.box-footer-->
  </div>
  <!-- /.box -->