routes/web.php
// Route::get('/person/sync', 'Admin\PersonController@sync')->name('loginadmin');

Route::post('/sendmailcontacts', 'Front\Home\FrontController@sendEmailcontact')->name('front.sendmailfront');

Auth::routes();

Route::group(['middleware' => ['auth', 'role', 'web'], 'prefix' => 'admin'], function(){
	Route::get('/', 'HomeController@index')->name('home');

	/// Module Persons
	Route::post('/persons/input-person-role/{user_id}/{role_id}', 'Admin\PersonController@inputPersonRole')->name('persons.input-person-role');
	Route::delete('/persons/delete-person-role/{id}', 'Admin\PersonController@deletePersonRole')->name('persons.delete-person-role');
	Route::get('persons/getAPI', 'Admin\PersonController@getAPI')->name('persons.getAPI');
	Route::get('/persons/edit-ajax/{id}', 'Admin\PersonController@editAjax')->name('person.edit-ajax');
	Route::get('/persons/person-role/{user_id}', 'Admin\PersonController@personRole')->name('person.person-role');
	Route::get('/persons/list-of-role/{user_id}', 'Admin\PersonController@listOfRole')->name('person.list-of-role');
	Route::resource('persons', 'Admin\PersonController');
	//// end module person

	////Module Company
	Route::get('companies/get-datatables-data/{parent?}', 'Admin\CompanyController@getDatatablesData')->name('companies.getdatatablesdata');
	Route::get('companies/get-employee/{id}', 'Admin\CompanyController@getEmployee')->name('companies.get-employee');
	Route::get('companies/get-related-company/{id}', 'Admin\CompanyController@getRelatedCompany')->name('companies.get-related-company');
	Route::post('companies/save-related-company', 'Admin\CompanyController@saveRelatedCompany')->name('companies.save-related-company');
	Route::resource('companies', 'Admin\CompanyController');
	/////end company

	////Module Contentmanagement
	Route::get('nodes/{parent?}/{lvl?}/ajaxnode', 'Admin\NodeController@publish2ajaxnode')->name('nodes.ajaxnode');
	Route::post('/nodes/{id}/edit/priority', 'Admin\NodeController@nodePriority')->name('nodes.editpriority');
	Route::post('/nodes/{id}/edit/unlink', 'Admin\NodeController@nodeUnLink')->name('nodes.editunlink');
	Route::post('/nodes/{id}/edit/{parent?}', 'Admin\NodeController@nodeLink')->name('nodes.editlink');
	Route::get('/nodes/content-text/{id}', 'Admin\NodeController@contentText')->name('nodes.content-text');
	Route::get('/nodes/content-img/{id}', 'Admin\NodeController@contentImg')->name('nodes.content-img');
	Route::get('/nodes/content-detail/{id}', 'Admin\NodeController@contentDet')->name('nodes.content-detail');
	Route::put('/nodes/content-text/{id}', 'Admin\NodeController@contentTextUpdate')->name('nodes.content-text-update');
	Route::put('/nodes/content-img/{id}', 'Admin\NodeController@contentImgUpdate')->name('nodes.content-img-update');
	Route::resource('nodes', 'Admin\NodeController');
	/////end Contentmanagement


	////Module Statement
	Route::get('statements/ajax-list/{parent?}/{level?}', 'admin\StatementController@statementAjaxList')->name('statements.ajax-list');
	Route::get('statements/get-data-tables-data/{id?}', 'admin\StatementController@getDatatablesData')->name('statements.get-data-tables-data');
	Route::put('statements/link-unlink/{id?}/{parent?}', 'admin\StatementController@linkUnlink')->name('statements.link-unlink');
	Route::put('statements/priority/', 'admin\StatementController@priority')->name('statements.priority');
	Route::get('statements/get-product/{id?}', 'admin\StatementController@getProductData')->name('statements.get-product');
	Route::get('statements/get-product-all/{id?}', 'admin\StatementController@getProductDataAll')->name('statements.get-product-all');
	Route::get('statements/edit-ajax/{id?}', 'admin\StatementController@editAjax')->name('statements.edit-ajax');
	Route::put('statements/edit-tablename/{id?}', 'admin\StatementController@editTablename')->name('statements.edit-tablename');
	Route::put('statements/product-link/{id}', 'admin\StatementController@productLink')->name('statements.product-link');
	Route::resource('statements', 'admin\StatementController');
	/////end Statement

	/// Module Language String
	Route::get('/languagestring/', 'admin\LanguagestringController@index')->name('languagestring');
	Route::get('/languagestring/getLangs', 'admin\LanguagestringController@getLangs')->name('languagestring.getLangs');
	Route::post('/languagestring/store', 'admin\LanguagestringController@store')->name('languagestring.storeLangs');
	/// End Module Language String

	/// Module Product
	Route::get('products/{id}/edit-ajax', 'Admin\ProductController@editAjax')->name('product.editajax');
	Route::get('products/{id}/edit-product-text', 'Admin\ProductController@editProductText')->name('product.editproducttext');
	Route::put('products/update-ajax/{id}', 'Admin\ProductController@updateAjax')->name('product.updateajax');
	Route::get('products/{id}/edit-product-media', 'Admin\ProductController@editProductMedia')->name('product.editproductmedia');
	Route::post('products/update-product-media/{id?}', 'Admin\ProductController@updateProductMediaAjax')->name('product.updateproductmediaajax');
	Route::delete('products/delete-product-media/{id}', 'Admin\ProductController@deleteProductMediaAjax')->name('product.deleteproductmediaajax');
	Route::get('products/get-datatables-data', 'Admin\ProductController@getDatatablesData')->name('products.getdatatablesdata');
	Route::resource('products', 'Admin\ProductController');
	/// End Module Product

	// Module order sale
	Route::get('/ordersale/getDatatablesData', 'admin\OrderSaleController@getDatatablesData')->name('ordersale.getDatatablesData');
	Route::get('/ordersale/delete/{id}/{table?}', 'admin\OrderSaleController@delete')->name('ordersale.delete');
	Route::get('/ordersale/invoiced/{id}', 'admin\OrderSaleController@invoiced')->name('ordersale.invoiced');
	// End Module order sale

	////Sync Db to Wisehouse
	Route::get('/sync', 'admin\SyncwisehouseController@index')->name('sync.index');
	Route::get('/sync/range-product', 'admin\SyncwisehouseController@syncRangeProduct')->name('sync.rangeproduct');
	Route::get('/sync/product', 'admin\SyncwisehouseController@syncProduct')->name('sync.product');
	Route::get('/sync/company', 'admin\SyncwisehouseController@syncCompany')->name('sync.company');
	Route::get('/sync/extraques/{limit?}/{offset?}', 'admin\SyncwisehouseController@syncExtraquestion')->name('sync.extraques');
	Route::get('/sync/role', 'admin\SyncwisehouseController@syncRole')->name('sync.role');
	Route::get('/sync/statement', 'admin\SyncwisehouseController@syncStatement')->name('sync.statement');
	////Sync Db to Wisehouse

	////Module Roles
	Route::get('roles/get-datatables-data', 'admin\RoleController@getDatatablesData')->name('roles.getdatatablesdata');
	Route::get('roles/role-action-list', 'admin\RoleController@getRoleActionList')->name('roles.get-role-action-list');
	Route::get('roles/get-datatables-data-action', 'admin\RoleController@getDatatablesDataAction')->name('roles.getdatatablesdataaction');
	Route::get('roles/role-action-create', 'admin\RoleController@roleActionCreate')->name('roles.role-action-create');
	Route::post('roles/role-action-store', 'admin\RoleController@roleActionStore')->name('roles.role-action-store');
	Route::get('roles/role-action-edit/{id}', 'admin\RoleController@roleActionEdit')->name('roles.role-action-edit');
	Route::put('roles/role-action-update/{id}', 'admin\RoleController@roleActionUpdate')->name('roles.role-action-update');
	Route::resource('roles', 'admin\RoleController');
	/////end Roles
});

Route::resources([
    '/post' => 'Admin\PostController',
    '/node' => 'Admin\NodeController',
    '/admin/ordersale' => 'Admin\OrderSaleController',
    '/admin/ordersubscriptions' => 'Admin\OrdersubscriptionsController',
    '/admin/invoice' => 'Admin\InvoiceController',
    '/admin/registrations' => 'Admin\RegistrationController'
]);


Route::get('no/profiles', 'Front\Profile\ProfileController@index')->name('profiles.no.index');
Route::get('en/profiles', 'Front\Profile\ProfileController@index')->name('profiles.en.index');
Route::get('no/om_oss/{content?}', 'Front\Home\FrontController@omoss')->name('om_oss');

// My profile
Route::get('api-web/v1/profile/', 'Front\Api\ProfileController@index')->name('api.profile.index');
Route::put('api-web/v1/profile/update/{id?}', 'Front\Api\ProfileController@update')->name('api.profile.update');
Route::get('api-web/v1/profile/update/{id?}', 'Front\Api\ProfileController@edit')->name('api.profile.edit');

Route::get('api-web/v1/profile/updatepassword/{id?}', 'Front\Api\ProfileController@editPassword')->name('api.profile.editpassword');
Route::put('api-web/v1/profile/passwordstore/{id?}', 'Front\Api\ProfileController@passwordStore')->name('api.profile.passwordstore');

Route::get('api-web/v1/profile/subscription', 'Front\Api\ProfileController@subscription')->name('api.profile.subscription');

Route::get('api-web/v1/profile/yesdoit', 'Front\Api\ProfileController@yesdoit')->name('api.profile.yesdoit');
Route::post('api-web/v1/profile/yesdoit', 'Front\Api\ProfileController@yesdoitstore')->name('api.profile.yesdoitstore');

Route::get('api-web/v1/profile/action', 'Front\Api\ProfileController@action')->name('api.profile.action');
Route::post('api-web/v1/profile/action', 'Front\Api\ProfileController@actionstore')->name('api.profile.actionstore');

// myanalyses
Route::get('api-web/v1/profile/myanalyses', 'Front\Api\MyanalyseController@index')->name('api.myanalyses.index');
Route::post('api-web/v1/profile/myanalysessave', 'Front\Api\MyanalyseController@save')->name('api.myanalyses.save');
Route::post('api-web/v1/profile/myanalysesadd', 'Front\Api\MyanalyseController@add')->name('api.myanalyses.add');
Route::get('api-web/v1/profile/liststatement/{mainnode}/{subnode?}/{tipe?}', 'Front\Api\MyanalyseController@liststatement')->name('api.myanalyses.liststatement');
Route::get('/no/profile/detailanalyses/{id}/{tipe?}/{year?}/{month?}', 'Front\Api\MyanalyseController@detail')->name('analyses.detail');

resources/views/admin/product/list.blade.php
@extends('admin.layouts.master')

@section('title') 
Product 
@endsection

@section('breadcrumb')
<h1>@yield('title')<!-- <small></small> --></h1>
<ol class="breadcrumb">
    <li><a href="{{ url('admin/') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active"><a href="{{ url('admin/product') }}">@yield('title')</a></li>
</ol>
@endsection

@section('css_custom')
<link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">
@endsection

@section('content')
	<section class="content">

		<div class="box collapsed-box">
	    <div class="box-header with-border">
	      <h3 class="box-title">Create New Product</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-plus"></i></button>
	      </div>
	    </div>
	    <div class="box-body" style="display: none;">
	      <div class="row">

	        <div class="col-xs-12">
	        	<a class="btn btn-success" href="{{ route('products.create') }}">Create New Product</a>
	        </div>

	      </div>

	    </div><!-- /.box-body -->
	  </div>

	  <!-- Default box -->
	  <div class="box">
	    <div class="box-header with-border">
	      <h3 class="box-title">Products</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	      </div>
	    </div>
	    <div class="box-body">
	      <div class="row">

	        <div class="col-xs-12">

	          	<div class="panel panel-default">
                	<div class="panel-heading">Product List</div>

	                <div class="panel-body">
	                    <table class="table table-hover table-bordered table-striped datatable" style="width:100%">
	                        <thead>
	                            <tr>
	                                <th>Id</th>
	                                <th>Product Number</th>
	                                <th>Product Name</th>
	                                <th>Classification</th>
	                                <th>Supplier</th>
	                                <th>Cost Price</th>
	                                <th>Cust Price</th>
	                                <th>Action</th>
	                            </tr>
	                        </thead>
	                    </table>
	            	</div>
	            </div>

	        </div>

	      </div>
	      <div class="ajax-content">
	      </div>
	    </div>
	    <!-- /.box-body -->
	    <div class="box-footer">
	      Footer
	    </div>
	    <!-- /.box-footer-->
	  </div>
	  <!-- /.box -->

	</section>
@endsection

@section('addingFileJs')
	<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
@endsection

@section('addingScriptJs')
	<script type="text/javascript">
	$(document).ready(function() {
	    var table = $('.datatable').DataTable({
	        processing: true,
	        serverSide: true,
	        ajax: '{{ route('products.getdatatablesdata') }}',
	        columns: [
	            {data: 'id', name: 'products.id'},
	            {data: 'ProductNumber', name: 'products.ProductNumber'},
	            {data: 'ProductName', name: 'producttexts.ProductName', orderable: true, searchable: true},
	            {data: 'ClassificationID', name: 'products.ClassificationID'},
	            {data: 'SupplierID', name: 'products.SupplierID'},
	            {data: 'UnitCostPrice', name: 'products.UnitCostPrice'},
	            {data: 'UnitCustPrice', name: 'products.UnitCustPrice'},
	            {data: 'action', name: 'action', orderable: false, searchable: false}
	        ]
	    });

	  //   $('body').on('click', '.savelang', function(){
	  //   	var formData = {
   //              language_id : $('#language_id').val(),
   //              language_string_text_id : $('#languagestringtextid').val(),
   //              language_string : $('#languagestring').val(),
   //              _token  : $('meta[name="csrf-token"]').attr('content'),
   //              _method: 'post',
   //              id: $('#langs-id').val(),
   //          }

   //          $.ajaxSetup({
			//     headers: {
			//         'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			//     }
			// });

			// if(formData.language_id == '' || formData.language_string_text_id == '' || formData.language_string == ''){
			// 	alert('Fill All Data.')
			// 	return false;
			// }

			// console.log(formData);

			// $.ajax({
	  //           type: 'post',
	  //           url: '{{ route('languagestring.storeLangs') }}',
	  //           data: formData,
	  //       }).done(function (data) {
	  //           if(data == 'Success'){
	  //           	alert(data);
	  //           	$('#langs-id').val('');
	  //           	$('#language_id').val('');
	  //   			$("#languagestringtextid").val('');
	  //   			$("#languagestring").val('');
	  //           	table.ajax.reload();
	  //           }else{
	  //           	alert(data);
	  //           }
	  //       });
	  //   });

	    // $("body").on('click', '.editLangs', function(){
	    // 	var id = $(this).attr('id');
	    // 		id = id.split("_");
	    // 		id = id[1];
	    // 		languageid = $(this).attr('languageid');
	    // 		textid = $(this).attr('textid');
	    // 		langstr = $(this).attr('langstr');
	    		
	    // 		$('#language_id').val(languageid);
	    // 		$("#languagestringtextid").val(textid);
	    // 		$("#languagestring").val(langstr);
	    // 		$("#langs-id").val(id);
	    // });
	});
	</script>
@endsection

resources/views/admin/product/productmedia.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="alert alert-info successProductMedia" style="display: none;">
    <p>Success save the data.</p>
</div>

<div style="margin-bottom: 15px;">
	<button class="btn btn-primary addproductmedia" type="button">New Product Image</button>
</div>

<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Product Media ( {{ $productmedia->id??null }} ) / Product ID ( {{ $product->id }} )</h3>
    <input type="hidden" id="ProductMediaID" value="" />

    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
              title="Collapse">
        <i class="fa fa-minus"></i></button>
    </div>
  </div>
    
  <div class="box-body">
    <div class="row row-media">

    	<input type="hidden" id="ProductID" value="{{ $product->id }}" />

    	@if($mediastorage != null)
    	@foreach($mediastorage as $keyMedia => $valMedia)
    		<div id="delete_{{ $valMedia->id }}">
		      <input type="hidden" name="mediastorage_id[]" value="{{ $valMedia->id }}" />

		      <div class="col-md-4">
		        <div class="gmbr-node">
		          <img src="{{ url('storage/'.$valMedia->path) }}" class="img-responsive gmbr-node-img" id="viewImg_{{ $keyMedia+1 }}" />
		        </div>
		      </div>

		      <div class="col-md-8">
		          <div class="form-group">
		            <label for="inputMedia1">File input</label>
		            <input type="file" class="form-control mediadb" name="mediadb[]" id="mediadb_{{ $keyMedia+1 }}" />
		            <br />
		            <input type="text" class="form-control" name="img_titledb[]" value="{{ $valMedia->title }}" />
		            <br />
		            <input type="text" class="form-control"
		            name="externalurldb[]" value="{{ $valMedia->external_url }}" placeholder="External Url" />
		            <br />
		            <a class="btn btn-danger deleteImg" data-method="delete" 
		            href="{{ route('product.deleteproductmediaajax', ['id' => $valMedia->id]) }}">
		            	Delete
		            </a>
		          </div>
		      </div>
		      <div class="clearfix" style="margin-bottom: 15px;"></div>
	      </div>
      @endforeach
      @endif

    </div><!-- row -->
  </div>
</div>

<div class="panel">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-offset-5 col-md-2 text-center">
				<a href="#" class="btn btn-default">Cancel</a>
				&nbsp;
				<input type="button" value="Save" class="btn btn-primary saveProductMedia" />
			</div>
		</div>
	</div>
</div>

resources/views/admin/product/producttext.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="alert alert-info successProductText" style="display: none;">
    <p>Success save the data.</p>
</div>

<div style="margin-bottom: 15px;">
	<button class="btn btn-primary" type="button">New Product Text</button>
</div>

<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Product text ( {{ $productText->LanguageID??null }} )</h3>
    <input type="hidden" id="ProductTextID" value="{{ $productText->id??null }}" />

    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
              title="Collapse">
        <i class="fa fa-minus"></i></button>
    </div>
  </div>
    
  <div class="box-body">
    <div class="row">

        <div class="col-xs-12">

          <div class="form-horizontal">

            	<div class="row">
            		<div class="col-md-6">
	                <div class="form-group">
	                  <label for="LanguageID" class="col-sm-3 control-label">Language</label>

	                  <div class="col-sm-9">
	                  	<select id="LanguageID" 
	                  	class="form-control productTextLanguage" target="{{ route('product.editproducttext', ['id' => $product->id]) }}">
	                  		<option value="">-------Select Language-------</option>
	                  		@foreach($langList as $ll)
	                  			@if($ll['key'] == $productText->LanguageID)
	                  				<option value="{{ $ll['key'] }}" selected>{{ $ll['value'] }}</option>
	                  			@else
	                  				<option value="{{ $ll['key'] }}">{{ $ll['value'] }}</option>
	                  			@endif
	                  		@endforeach
	                  	</select>
	                    {{-- <input type="text" class="form-control" value="{{ $product->ProductNumber or old('ProductNumber') }}" 
	                    placeholder="Product Number" name="ProductNumber" /> --}}
	                  </div>
	                </div>
	                <div class="form-group">
	                  <label for="ProductName" class="col-sm-3 control-label">Product Name</label>

	                  <div class="col-sm-9">
	                    <input type="text" class="form-control" value="{{ $productText->ProductName or old('ProductName') }}" 
	                    placeholder="Product Name" id="ProductName">
	                  </div>
	                </div>

	                <div class="form-group">
	                  <label for="TeaserText" class="col-sm-3 control-label">Teaser Text</label>

	                  <div class="col-sm-9">
	                  	<textarea name="TeaserText"
	                  		class="form-control" rows="10">{{ $productText->TeaserText or old('TeasetText') }}</textarea>
	                  </div>
	                </div>

	                <div class="form-group">
	                  <label for="SalesText" class="col-sm-3 control-label">Sales Text</label>

	                  <div class="col-sm-9">
	                  	<textarea name="SalesText" 
	                  		class="form-control" rows="10">{{ $productText->SalesText or old('SalesText') }}</textarea>
	                  </div>
	                </div>

	                <div class="form-group">
	                  <label for="ProductText" class="col-sm-3 control-label">Functions</label>

	                  <div class="col-sm-9">
	                  	<textarea name="ProductText" 
	                  		class="form-control" rows="10">{{ $productText->ProductText or old('ProductText') }}</textarea>
	                  </div>
	                </div>

	                <div class="form-group">
	                  <label for="TechnicalText" class="col-sm-3 control-label">Technical text</label>

	                  <div class="col-sm-9">
	                  	<textarea name="TechnicalText" 
	                  		class="form-control" rows="10">{{ $productText->TechnicalText or old('TechnicalText') }}</textarea>
	                  </div>
	                </div>

	                <div class="form-group">
	                  <label for="FeatureText" class="col-sm-3 control-label">Description</label>

	                  <div class="col-sm-9">
	                  	<textarea name="FeatureText" 
	                  		class="form-control" rows="10">{{ $productText->FeatureText or old('FeatureText') }}</textarea>
	                  </div>
	                </div>
                </div>
                <div class="col-md-6">
                	<div>&nbsp;</div>
                </div>
              </div>
          </div>

      	</div>

    </div><!-- /.box-body -->
  </div>
</div>

<div class="panel">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-offset-5 col-md-2 text-center">
				<a href="#" class="btn btn-default">Cancel</a>
				&nbsp;
				<input type="button" value="Save" class="btn btn-primary saveProductText" />
			</div>
		</div>
	</div>
</div>