routes/web.php
Route::get('/', 'Front\Home\FrontController@index')->name('front.home');
Route::get('/changelanguage/{langID?}', 'Front\Home\FrontController@changeLanguage')->name('changeLanguage');

Route::get('/loginadmin', 'Auth\LoginController@loginadmin')->name('loginadmin');
// Route::get('/loginfront', 'Auth\LoginController@registerfront')->name('loginfront');
Route::get('/registerfronts', 'Front\Home\FrontController@registerfront')->name('registerfronts');
Route::post('/loginfront', 'Auth\LoginController@storeloginfront')->name('storeloginfront');

// Route::get('/person/sync', 'Admin\PersonController@sync')->name('loginadmin');

Route::post('/sendmailcontacts', 'Front\Home\FrontController@sendEmailcontact')->name('front.sendmailfront');

Auth::routes();

Route::group(['middleware' => ['auth', 'role', 'web'], 'prefix' => 'admin'], function(){
	Route::get('/', 'HomeController@index')->name('home');

	/// Module Persons
	Route::post('/persons/input-person-role/{user_id}/{role_id}', 'Admin\PersonController@inputPersonRole')->name('persons.input-person-role');
	Route::delete('/persons/delete-person-role/{id}', 'Admin\PersonController@deletePersonRole')->name('persons.delete-person-role');
	Route::get('persons/getAPI', 'Admin\PersonController@getAPI')->name('persons.getAPI');
	Route::get('/persons/edit-ajax/{id}', 'Admin\PersonController@editAjax')->name('person.edit-ajax');
	Route::get('/persons/person-role/{user_id}', 'Admin\PersonController@personRole')->name('person.person-role');
	Route::get('/persons/list-of-role/{user_id}', 'Admin\PersonController@listOfRole')->name('person.list-of-role');
	Route::resource('persons', 'Admin\PersonController');
	//// end module person

	////Module Company
	Route::get('companies/get-datatables-data/{parent?}', 'Admin\CompanyController@getDatatablesData')->name('companies.getdatatablesdata');
	Route::get('companies/get-employee/{id}', 'Admin\CompanyController@getEmployee')->name('companies.get-employee');
	Route::get('companies/get-related-company/{id}', 'Admin\CompanyController@getRelatedCompany')->name('companies.get-related-company');
	Route::post('companies/save-related-company', 'Admin\CompanyController@saveRelatedCompany')->name('companies.save-related-company');
	Route::resource('companies', 'Admin\CompanyController');
	/////end company

	////Module Contentmanagement
	Route::get('nodes/{parent?}/{lvl?}/ajaxnode', 'Admin\NodeController@publish2ajaxnode')->name('nodes.ajaxnode');
	Route::post('/nodes/{id}/edit/priority', 'Admin\NodeController@nodePriority')->name('nodes.editpriority');
	Route::post('/nodes/{id}/edit/unlink', 'Admin\NodeController@nodeUnLink')->name('nodes.editunlink');
	Route::post('/nodes/{id}/edit/{parent?}', 'Admin\NodeController@nodeLink')->name('nodes.editlink');
	Route::get('/nodes/content-text/{id}', 'Admin\NodeController@contentText')->name('nodes.content-text');
	Route::get('/nodes/content-img/{id}', 'Admin\NodeController@contentImg')->name('nodes.content-img');
	Route::get('/nodes/content-detail/{id}', 'Admin\NodeController@contentDet')->name('nodes.content-detail');
	Route::put('/nodes/content-text/{id}', 'Admin\NodeController@contentTextUpdate')->name('nodes.content-text-update');
	Route::put('/nodes/content-img/{id}', 'Admin\NodeController@contentImgUpdate')->name('nodes.content-img-update');
	Route::resource('nodes', 'Admin\NodeController');
	/////end Contentmanagement


	////Module Statement
	Route::get('statements/ajax-list/{parent?}/{level?}', 'admin\StatementController@statementAjaxList')->name('statements.ajax-list');
	Route::get('statements/get-data-tables-data/{id?}', 'admin\StatementController@getDatatablesData')->name('statements.get-data-tables-data');
	Route::put('statements/link-unlink/{id?}/{parent?}', 'admin\StatementController@linkUnlink')->name('statements.link-unlink');
	Route::put('statements/priority/', 'admin\StatementController@priority')->name('statements.priority');
	Route::get('statements/get-product/{id?}', 'admin\StatementController@getProductData')->name('statements.get-product');
	Route::get('statements/get-product-all/{id?}', 'admin\StatementController@getProductDataAll')->name('statements.get-product-all');
	Route::get('statements/edit-ajax/{id?}', 'admin\StatementController@editAjax')->name('statements.edit-ajax');
	Route::put('statements/edit-tablename/{id?}', 'admin\StatementController@editTablename')->name('statements.edit-tablename');
	Route::put('statements/product-link/{id}', 'admin\StatementController@productLink')->name('statements.product-link');
	Route::resource('statements', 'admin\StatementController');
	/////end Statement

	/// Module Language String
	Route::get('/languagestring/', 'admin\LanguagestringController@index')->name('languagestring');
	Route::get('/languagestring/getLangs', 'admin\LanguagestringController@getLangs')->name('languagestring.getLangs');
	Route::post('/languagestring/store', 'admin\LanguagestringController@store')->name('languagestring.storeLangs');
	/// End Module Language String

	/// Module Product
	Route::get('products/{id}/edit-ajax', 'Admin\ProductController@editAjax')->name('product.editajax');
	Route::get('products/{id}/edit-product-text', 'Admin\ProductController@editProductText')->name('product.editproducttext');
	Route::put('products/update-ajax/{id}', 'Admin\ProductController@updateAjax')->name('product.updateajax');
	Route::get('products/{id}/edit-product-media', 'Admin\ProductController@editProductMedia')->name('product.editproductmedia');
	Route::post('products/update-product-media/{id?}', 'Admin\ProductController@updateProductMediaAjax')->name('product.updateproductmediaajax');
	Route::delete('products/delete-product-media/{id}', 'Admin\ProductController@deleteProductMediaAjax')->name('product.deleteproductmediaajax');
	Route::get('products/get-datatables-data', 'Admin\ProductController@getDatatablesData')->name('products.getdatatablesdata');
	Route::resource('products', 'Admin\ProductController');
	/// End Module Product

	// Module order sale
	Route::get('/ordersale/getDatatablesData', 'admin\OrderSaleController@getDatatablesData')->name('ordersale.getDatatablesData');
	Route::get('/ordersale/delete/{id}/{table?}', 'admin\OrderSaleController@delete')->name('ordersale.delete');
	Route::get('/ordersale/invoiced/{id}', 'admin\OrderSaleController@invoiced')->name('ordersale.invoiced');
	// End Module order sale

	////Sync Db to Wisehouse
	Route::get('/sync', 'admin\SyncwisehouseController@index')->name('sync.index');
	Route::get('/sync/range-product', 'admin\SyncwisehouseController@syncRangeProduct')->name('sync.rangeproduct');
	Route::get('/sync/product', 'admin\SyncwisehouseController@syncProduct')->name('sync.product');
	Route::get('/sync/company', 'admin\SyncwisehouseController@syncCompany')->name('sync.company');
	Route::get('/sync/extraques/{limit?}/{offset?}', 'admin\SyncwisehouseController@syncExtraquestion')->name('sync.extraques');
	Route::get('/sync/role', 'admin\SyncwisehouseController@syncRole')->name('sync.role');
	Route::get('/sync/statement', 'admin\SyncwisehouseController@syncStatement')->name('sync.statement');
	////Sync Db to Wisehouse

	////Module Roles
	Route::get('roles/get-datatables-data', 'admin\RoleController@getDatatablesData')->name('roles.getdatatablesdata');
	Route::get('roles/role-action-list', 'admin\RoleController@getRoleActionList')->name('roles.get-role-action-list');
	Route::get('roles/get-datatables-data-action', 'admin\RoleController@getDatatablesDataAction')->name('roles.getdatatablesdataaction');
	Route::get('roles/role-action-create', 'admin\RoleController@roleActionCreate')->name('roles.role-action-create');
	Route::post('roles/role-action-store', 'admin\RoleController@roleActionStore')->name('roles.role-action-store');
	Route::get('roles/role-action-edit/{id}', 'admin\RoleController@roleActionEdit')->name('roles.role-action-edit');
	Route::put('roles/role-action-update/{id}', 'admin\RoleController@roleActionUpdate')->name('roles.role-action-update');
	Route::resource('roles', 'admin\RoleController');
	/////end Roles
});

Route::resources([
    '/post' => 'Admin\PostController',
    '/node' => 'Admin\NodeController',
    '/admin/ordersale' => 'Admin\OrderSaleController',
    '/admin/ordersubscriptions' => 'Admin\OrdersubscriptionsController',
    '/admin/invoice' => 'Admin\InvoiceController',
    '/admin/registrations' => 'Admin\RegistrationController'
]);


Route::get('no/profiles', 'Front\Profile\ProfileController@index')->name('profiles.no.index');
Route::get('en/profiles', 'Front\Profile\ProfileController@index')->name('profiles.en.index');
Route::get('no/om_oss/{content?}', 'Front\Home\FrontController@omoss')->name('om_oss');

// My profile
Route::get('api-web/v1/profile/', 'Front\Api\ProfileController@index')->name('api.profile.index');
Route::put('api-web/v1/profile/update/{id?}', 'Front\Api\ProfileController@update')->name('api.profile.update');
Route::get('api-web/v1/profile/update/{id?}', 'Front\Api\ProfileController@edit')->name('api.profile.edit');

Route::get('api-web/v1/profile/updatepassword/{id?}', 'Front\Api\ProfileController@editPassword')->name('api.profile.editpassword');
Route::put('api-web/v1/profile/passwordstore/{id?}', 'Front\Api\ProfileController@passwordStore')->name('api.profile.passwordstore');

Route::get('api-web/v1/profile/subscription', 'Front\Api\ProfileController@subscription')->name('api.profile.subscription');

Route::get('api-web/v1/profile/yesdoit', 'Front\Api\ProfileController@yesdoit')->name('api.profile.yesdoit');
Route::post('api-web/v1/profile/yesdoit', 'Front\Api\ProfileController@yesdoitstore')->name('api.profile.yesdoitstore');

Route::get('api-web/v1/profile/action', 'Front\Api\ProfileController@action')->name('api.profile.action');
Route::post('api-web/v1/profile/action', 'Front\Api\ProfileController@actionstore')->name('api.profile.actionstore');

// myanalyses
Route::get('api-web/v1/profile/myanalyses', 'Front\Api\MyanalyseController@index')->name('api.myanalyses.index');

resources/views/admin/statements/ajax-list.blade.php
<div class="lvl1 ajavlvl{{ $lvl }}load">
	<div class="h-new-node">
		<img src="{{ asset('images/folder1.png') }}" class="img-responsive" />
	</div>
	<div class="h-new-title">
		<a href="{{ route('statements.create', ['parent' => $parent, 'lvl' => $lvl]) }}">New Node</a>
	</div>

	<div class="clearfix"></div>

	<div class="b-node">
		@foreach($statementstr as $s)
			@if($s->statement['id'] != null and $s->statement['active'] == 1)
				<div class="c-menu-b">
					<div class="h-new-node">
						<a href="{{ route('statements.index', ['parent' => $s->statement['id'], 'lvl' => $lvl]) }}" class="lvl{{ $lvl }}clicked" id="{{ $s->statement['id'] }}">
		  				<img src="{{ asset('images/folder1.png') }}" class="img-responsive" />
		  			</a>
		  		</div>
		  		<div class="h-new-title">
		  			<a href="{{ route('statements.edit', ['id' => $s->statement['id'], 'parent' => $parent, 'lvl' => $lvl]) }}">
		  				{{ $s->statement['title'] }} ({{ $s->statement['id'] }})
		  			</a>
		  		</div>

		  		<div class="clearfix"></div>
				</div>
			@endif
		@endforeach

	</div>
</div>

resources/views/admin/statements/create.blade.php
@extends('admin.layouts.master')

@section('title') 
Create Statement
@endsection

@section('breadcrumb')
<h1>@yield('title')<!-- <small></small> --></h1>
<ol class="breadcrumb">
    <li><a href="{{ url('admin/') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active"><a href="{{ url('admin/statements') }}">Statement</a></li>
    <li class="active"><a href="{{ route('statements.create') }}">@yield('title')</a></li>
</ol>
@endsection

@section('content')
	<section class="content">

		<form action="{{ route('statements.store', ['parent' => $parent, 'lvl' => session()->get('lvl1Val')]) }}" method="post" enctype="multipart/form-data" id="upload_form">
		{{ csrf_field() }}
		@if(isset($statement->id))
			<input type="hidden" name="id" value="{{ $statement->id }}" />
			<input type="hidden" name="_method" value="PUT" />
		@endif

			<input type="hidden" name="InsertedByPersonID" value="{{ Auth::user()->id }}" />
			<input type="hidden" name="UpdatedByPersonID" value="{{ Auth::user()->id }}" />
			<input type="hidden" name="tablename" value="statements" />
			<input type="hidden" name="primarykey" value="0" />

		<div id="ajaxLoad">

		@if ($errors->any())
		    <div class="alert alert-danger">
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </div>
		@endif

		@if (\Session::has('success'))
      <div class="alert alert-success">
          <p>{{ \Session::get('success') }}</p>
      </div><br />
    @endif

		<div class="box box-success">
	    <div class="box-header with-border">
	      <h3 class="box-title">Statement Data</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	      </div>
	    </div>
		    
		  <div class="box-body">
		    <div class="row">

		        <div class="col-xs-12">

              <div class="form-horizontal">

	              	<div class="row">
	              		<div class="col-md-6">

	              			<div class="form-group">
			                  <label for="title" class="col-sm-3 control-label">Statement Title</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $statement->title or old('title') }}" placeholder="Statement Title name" name="title">
			                  </div>
			                </div>

			                <div class="form-group">
			                  <label for="description" class="col-sm-3 control-label">Description</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $statement->description or old('description') }}" placeholder="Description" 
			                    name="description">
			                  </div>
			                </div>
			                
		                </div>

		                {{-- ////////////////Kanan////////////////////// --}}
		                <div class="col-md-6">
		                	
		                	<div class="form-group">
			                  <label for="active" class="col-sm-3 control-label">Active</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $statement->active or old('active') }}" placeholder="Active" name="active">
			                  </div>
			                </div>

			                
			                {{-- <div class="form-group">
			                  <label for="primarykey" class="col-sm-3 control-label">Primary Key</label>

			                  <div class="col-sm-9">
			                  	<input type="text" class="form-control" 
			                    value="{{ $statement->primarykey or old('primarykey') }}" placeholder="Description" 
			                    name="primarykey">
			                  </div>
			                </div> --}}

		                </div>
	                </div>
	            </div>

		      	</div>

		    </div><!-- /.box-body -->
		  </div>
		</div>

	  <div class="panel">
			<div class="panel-body">
				<div class="row">
					<div class="col-md-offset-5 col-md-2 text-center">
						<a href="#" class="btn btn-default">Cancel</a>
						&nbsp;
						<input type="submit" value="Save" class="btn btn-primary" />
					</div>
				</div>
			</div>
		</div>

		</div> {{-- ///////////////Ajax Call///////////// --}}

		</form>

	</section>
@endsection

@section('addingScriptJs')
	<script type="text/javascript">
	$(document).ready(function() {
			
	});
	</script>
@endsection

resources/views/admin/statements/edit-ajax.blade.php
<div class="box box-success">
	    <div class="box-header with-border">
	      <h3 class="box-title">Statement Data</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	      </div>
	    </div>
		    
		  <div class="box-body">
		    <div class="row">

		        <div class="col-xs-12">

              <div class="form-horizontal">

	              	<div class="row">
	              		<div class="col-md-6">

	              			<div class="form-group">
			                  <label for="title" class="col-sm-3 control-label">Statement Title</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $statement->title or old('title') }}" placeholder="Statement Title name" name="title">
			                  </div>
			                </div>

			                <div class="form-group">
			                  <label for="description" class="col-sm-3 control-label">Description</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $statement->description or old('description') }}" placeholder="Description" 
			                    name="description">
			                  </div>
			                </div>
			                
		                </div>

		                {{-- ////////////////Kanan////////////////////// --}}
		                <div class="col-md-6">
		                	
		                	<div class="form-group">
			                  <label for="active" class="col-sm-3 control-label">Active</label>
			                  <div class="col-sm-9">
			                    <input type="text" class="form-control" 
			                    value="{{ $statement->active or old('active') }}" placeholder="Active" name="active">
			                  </div>
			                </div>

		                </div>
	                </div>
	            </div>

		      	</div>

		    </div><!-- /.box-body -->
		  </div>
		</div>


	  <div class="panel">
			<div class="panel-body">
				<div class="row">
					<div class="col-md-offset-5 col-md-2 text-center">
						<a href="{{ route('logout') }}" onclick="event.preventDefault();
            document.getElementById('delete-statement').submit();" class="btn btn-danger">Delete</a>
						&nbsp;
						<input type="submit" value="Save" class="btn btn-primary" />
					</div>
				</div>
			</div>
		</div>

		</div> {{-- ///////////////Ajax Call///////////// --}}

		</form>

		<form id="delete-statement" action="{{ route('statements.destroy',$statement->id) }}" method="POST" style="display: none;">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE" />
    </form>


    <div class="box box-success">
	    <div class="box-header with-border">
	      <h3 class="box-title">Child Statement</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	      </div>
	    </div>
		    
		  <div class="box-body">
		    <div class="row">

		        <div class="col-xs-12">

              <div class="form-horizontal">

	              	<div class="row">
	  								<div class="col-md-12">
	  									
	  									<div class="panel panel-default">

			                	<div class="panel-heading">Child Statement List</div>

				                <div class="panel-body" id="ajaxChild">
				                	<div  id="ajaxChildLoad">
				                    <table class="table table-hover table-bordered table-striped" style="width:100%">
				                        <thead>
				                            <tr>
				                                <th>No</th>
				                                <th>Title</th>
				                                <th>Action</th>
				                                <th>Priority</th>
				                            </tr>
				                        </thead>
				                        <tbody>
				                        	@foreach($statementchildstr as $key => $st)
				                        	<tr>
				                        		<td>{{ $key+1 }}</td>
				                        		<td>{{ $st->title }} ( {{ $st->child_id }} )</td>
				                        		<td><a href="{{ route('statements.link-unlink', ['id' => $st->id, 'parent' => $statement->id, 'link' => 0]) }}"
                            						class="unlink" id="{{ $st->id }}" data-method="PUT">Unlink</a></td>
				                        		<td><input type="text" id="{{ $st->id }}" class="form-control priorityChild" value="{{ $st->priority }}"/></td>
				                        	</tr>
				                        	@endforeach
				                        </tbody>
				                    </table>
				                    <div class="pull-right">
				                    	<button type="button" class="btn btn-success savePriority">Save Priority</button>
				                    </div>

				                    <div style="clear: both"></div>
				                  </div>
				            		</div>

					            </div>

	  								</div>
	                </div>
	            </div>

		      	</div>

		    </div><!-- /.box-body -->
		  </div>
		</div>



		<div class="box box-success">
	    <div class="box-header with-border">
	      <h3 class="box-title">All Statement</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	      </div>
	    </div>
		    
		  <div class="box-body">
		    <div class="row">

		        <div class="col-xs-12">

              <div class="form-horizontal">

	              	<div class="row">
	  								<div class="col-md-12">
	  									
	  									<div class="panel panel-default">

			                	<div class="panel-heading">Statement List</div>

				                <div class="panel-body">
				                    <table class="table table-hover table-bordered table-striped datatable" style="width:100%">
				                        <thead>
				                            <tr>
				                                <th>Id</th>
				                                <th>Title</th>
				                                <th>Action</th>
				                            </tr>
				                        </thead>
				                        
				                    </table>
				            		</div>

					            </div>

	  								</div>
	                </div>
	            </div>

		      	</div>

		    </div><!-- /.box-body -->
		  </div>
		</div>

resources/views/admin/statements/index.blade.php
@extends('admin.layouts.master')

@section('title') 
Statement
@endsection

@section('breadcrumb')
<h1>@yield('title')<!-- <small></small> --></h1>
<ol class="breadcrumb">
    <li><a href="{{ url('admin/') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active"><a href="{{ url('admin/statements') }}">@yield('title')</a></li>
</ol>
@endsection

@section('content')
	<section class="content">

		@if (\Session::has('success'))
      <div class="alert alert-success">
          <p>{{ \Session::get('success') }}</p>
      </div><br />
    @endif

	  <!-- Default box -->
	  <div class="box">
	    <div class="box-header with-border">
	      <h3 class="box-title">Statement Page</h3>

	      <div class="box-tools pull-right">
	        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
	                title="Collapse">
	          <i class="fa fa-minus"></i></button>
	        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
	          <i class="fa fa-times"></i></button>
	      </div>
	    </div>
	    <div class="box-body">
	      <div class="row">
	      	<div class="col-md-2">
	      		<div class="lvl1">
		      		<div class="h-new-node">
		      			<img src="{{ asset('images/folder1.png') }}" class="img-responsive" />
		      		</div>
		      		<div class="h-new-title">
		      			<a href="{{ route('statements.create', ['parent' => session()->get('lvl1Val'), 'lvl' => 1]) }}">New Statement</a>
		      		</div>

		      		<div class="clearfix"></div>

		      		<div class="b-node">
		      			@foreach($statementstr as $statement)
			      			@if($statement->statement['id'] != null and $statement->statement['active'] == 1)
				      			<div class="c-menu-b">
					      			<div class="h-new-node">
					      				<a href="{{ route('statements.index', ['parent' => $statement->statement['id'], 'lvl' => 2]) }}"
					      					id="{{ $statement->statement['id'] }}" class="lvl1clicked">
						      				<img src="{{ asset('images/folder1.png') }}" class="img-responsive" />
						      			</a>
						      		</div>
						      		<div class="h-new-title">
						      			<a href="{{ route('statements.edit', ['id' => $statement->statement['id'], 'parent' => 0, 'lvl' => 1]) }}">
						      				{{ $statement->statement['title'] }} ({{ $statement->statement['id'] }})
						      			</a>
						      		</div>

						      		<div class="clearfix"></div>
					      		</div>
					      	@endif
			      		@endforeach

		      		</div>
	      		</div>

	      		<hr />
	      	</div>

	      	<div class="col-md-2 ajavlvl2">
	      		<hr />
	      	</div>

	      	<div class="col-md-2 ajavlvl3">
	      		<hr />
	      	</div>

	      	<div class="col-md-2 ajavlvl4">
	      		<hr />
	      	</div>

	      	<div class="col-md-2 ajavlvl5">
	      		<hr />
	      	</div>

	      </div>
	    </div>
	    <!-- /.box-body -->
	    <div class="box-footer">
	      Footer
	    </div>
	    <!-- /.box-footer-->
	  </div>
	  <!-- /.box -->

	</section>
@endsection



{{-- /////////////////////////Jquery//////////////////////////////////// --}}
@section('addingScriptJs')
  <script type="text/javascript">

    $(document).ready(function(){

      $("body").on('click', '.lvl1clicked', function(e){
      	e.preventDefault();
      	var Parent = "{{ URL::asset('/admin/statements/ajax-list') }}/"+$(this).attr('id')+"/2";
      	$(".ajavlvl2").load(Parent);
      	$(".ajavlvl3load").remove();
      	$(".ajavlvl4load").remove();
      	$(".ajavlvl5load").remove();
      });

      $("body").on('click', '.lvl2clicked', function(e){
      	e.preventDefault();
      	var Parent = "{{ URL::asset('/admin/statements/ajax-list') }}/"+$(this).attr('id')+"/3";
      	$(".ajavlvl3").load(Parent);
      	$(".ajavlvl4load").remove();
      	$(".ajavlvl5load").remove();
      });

      $("body").on('click', '.lvl3clicked', function(e){
      	e.preventDefault();
      	var Parent = "{{ URL::asset('/admin/statements/ajax-list') }}/"+$(this).attr('id')+"/4";
      	$(".ajavlvl4").load(Parent);
      	$(".ajavlvl5load").remove();
      	//$(".ajavlvl4load").remove();
      });

      $("body").on('click', '.lvl4clicked', function(e){
      	e.preventDefault();
      	var Parent = "{{ URL::asset('/admin/statements/ajax-list') }}/"+$(this).attr('id')+"/5";
      	$(".ajavlvl5").load(Parent);
      	//$(".ajavlvl4load").remove();
      });

    });

  </script>
@endsection